[build]
  command = "npm run build"
  publish = "dist/client/"

[[redirects]]
  from = '/nl/*'
  to = '/nl/layouts/error/404/index.html'
  status = 404

[[redirects]]
  from = '/en/*'
  to = '/en/layouts/error/404/index.html'
  status = 404
